---
title: "Project3 Analysis"
author: "Yuying Lu"
date: "2025-03-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
library(readxl)
library(ggplot2)
```

```{r}
baseline <- read.csv("baseline.csv")
endpoints <- read.csv("endpoints.csv")


base_df = baseline |> 
  mutate(
    ptid = factor(ptid),
    seq = paste0(
      substr(period1, nchar(period1), nchar(period1)),
      substr(period2, nchar(period2), nchar(period2)),
      substr(period3, nchar(period3), nchar(period3))),
    seq2 = case_when(
      period3=="Gel C" ~ 0,
      period3=="Gel B" ~ 1,
      period3=="Pill A" ~ 2),
    b1 = bviral1-bviral0,
    b2 = bviral3-bviral2,
    b3 = bviral5-bviral4,
    b4 = bviral6,
    s1 = sviral1-sviral0,
    s2 = sviral3-sviral2,
    s3 = sviral5-sviral4,
    s4 = sviral6) |> 
    select(ptid, seq, seq2, age, race, gender, b1, b2, b3, b4,
           s1, s2, s3, s4) |> 
    pivot_longer(b1:s4,
                 names_to = "index",
                 values_to = "viral") |> 
    mutate(period=substr(index,2,2),
           index = ifelse(substr(index,1,1)=="b","bviral","sviral")) |> 
  pivot_wider(names_from = index,
              values_from = viral)
 
endpoints 
end_df
end_df = 
  endpoints |> mutate(
    ptid = factor(ptid),
    seq = paste0(
      substr(period1, nchar(period1), nchar(period1)),
      substr(period2, nchar(period2), nchar(period2)),
      substr(period3, nchar(period3), nchar(period3))),
    seq2 = case_when(
      period3=="Gel C" ~ 0,
      period3=="Gel B" ~ 1,
      period3=="Pill A" ~ 2)) |> 
  pivot_longer(AE_pillA_week1:Adhere_gelC_week4,
               names_to = "index",
               values_to = "value") |> 
  select(ptid, seq, seq2, index, value) |> 
  mutate(week = substr(index,nchar(index),nchar(index)),
         treatment = str_sub(index, -7, -7),
         period =str_locate(seq, str_sub(index, -7, -7))[, "start"],
         index = str_sub(index,1,2)) |> 
  pivot_wider(names_from = index,
              values_from = value)

df <- 
  merge(end_df, base_df, by = c("ptid","seq","seq2","period")) |> 
  mutate(
    ptid= factor(ptid),
    period = factor(period),
    week = factor(week),
    seq  = factor(seq),
    seq2 = factor(seq2)
  )

df
```










```{r}
pri_df <- df %>%
  group_by(ptid, period, treatment) %>%
  summarise(
    age = first(age),
    race = first(race),
    gender = first(gender),
    seq = first(seq),
    seq2 = first(seq2),
    AE = ifelse(sum(AE)>=1,1,0),
    Ad = sum(Ad),
    .groups = "drop"
  )
pri_df 

```

# Primary Objective


```{r}
ad_mod <- lmer(Ad ~ treatment + period + (1|ptid), data = pri_df)
summary(ad_mod)
```




